name: Send Message Genie

on:
  schedule:
    # https://crontab.guru/#0_1_*_*_*
    - cron: "0 4 * * 1-5"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.4.0"

      - name: Send message
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: |
          npm i
          npm run start
