name: Send Message Genie

on:
  schedule:
    # https://crontab.guru/#0_1_*_*_*
    - cron: "* * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.4.0"
      - name: Generate Environment Variables
        run: |
          echo "SLACK_URL=$SLACK_URL" >> .env
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}

      - name: Send message
        run: |
          npm i
          npm run start
